fixed indentation
Was throwing these errors in current rendition of ZAP, so I removed all of the spaces that were used as tab space in the lines of code that followed.
  File "<script>", line 22
    uri = msg.getRequestHeader().getURI().toString()
    ^
IndentationError: unindent does not match any outer indentation level
  File "<script>", line 22
    uri = msg.getRequestHeader().getURI().toString()
    ^